# Subnet ids for worker nodes to be created in
subnetIds: ""

# The cluster name to identify the cluster
clusterName: ""

# VPC ID for the worker nodes to be created in
targetVpcId: ""

# The region to create the cluster in
region: ""

# Cluster endpoint used by karpernter
clusterEndpoint: ""

# IAM roles used by cloud-controller-manager, ebs-csi-driver, load-balancer-controller, karpenter
ccmRoleArn: ""
ebsCsiRoleArn: ""
lbControllerRoleArn: ""
karpenterRoleArn: ""

# AWS account id used by service acorn
awsAccountId: ""

# AWS IAM role arn used by service acorn
acornManagedRoleArn: ""

# AWS OIDC provider arn used by service acorn
awsIdentityProviderArn: "oidc"

# Cluster agent account url, token and name used by cluster agent
clusterAgentAccountUrl: ""
clusterAgentToken: ""
clusterAgentAccountName: ""
hubUrl: ""

# Acorn tag to install in the cluster
acornTag: "main"

# Options to turn on/off components
awsCcm: true
awsEbs: true
awsIdentity: true
awsLBController: true
certManager: true
coredns: true
traefik: true
acorn: true
awsKarpenter: true
hubResources: true
awsKarpenterProvisioner: true
istio: true

# For specifying if the cluster is a sandbox cluster
sandbox: false

# Prometheus configuration
# CFN output values.
# prometheusRemoteWriteEndpoint should have '/api/v1/remote_write' appended.
# prometheusRoleArn is the role used to assume prometheusRemoteWriteRoleArn, which is the role that can remote write metrics to AMP
prometheusRemoteWriteEndpoint: ""
prometheusRoleArn: ""
prometheusRemoteWriteRoleArn: ""
prometheus: true
# after prom chart install
prometheusInstance: false
