vpcId: ""

subnetIds: ""

clusterName: ""

roleArn: ""

targetVpcId: ""

region: ""

clusterEndpoint: ""

awsCcm: true
awsEbs: true
awsIdentity: true
awsLBController: true
certManager: true
coredns: true
traefik: true
acorn: true
awsKarpenter: true
awsKarpenterChart: true