{{ if .Values.hubResources }}
apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: cluster-agent
  namespace: acorn
spec:
  autoUpgrade: true
  autoUpgradeInterval: 15s
  profiles:
    - cluster-agent
  deployArgs:
    {{ if .Values.clusterAgentAccountUrl }}
    accountFqdn: {{ .Values.clusterAgentAccountUrl }}
    {{ end }}
    region: {{ .Values.region }}
    {{ if .Values.clusterAgentAccountName }}
    accountName: {{ .Values.clusterAgentAccountName }}
    {{ end }}
    hubUrl: {{ .Values.hubUrl }}
  image: "ghcr.io/acorn-io/hub:{{ .Values.acornTag }}"
  labels:
    - key: "sidecar.istio.io/inject"
      value: "false"
      resourceType: container
  permissions:
    - rules:
        - scopes:
            - cluster
          apiGroups:
            - '*'
          resources:
            - '*'
          verbs:
            - get
            - list
            - watch
            - update
            - patch
            - delete
            - deletecollection
            - create
      serviceName: cluster-agent

  secrets:
    - target: token-cluster-agent
      secret: token-cluster-agent
---
apiVersion: v1
kind: Secret
metadata:
  name: token-cluster-agent
  namespace: acorn
type: secrets.acorn.io/token
data:
  token: {{ .Values.clusterAgentToken | b64enc }}
---
apiVersion: internal.admin.acorn.io/v1
cpuScaler: 0.25
default: true
description: Default offering
kind: ClusterComputeClassInstance
memory: {}
metadata:
  name: default
---
apiVersion: internal.admin.acorn.io/v1
default: true
description: Project compute class for Hub resources
kind: ProjectComputeClassInstance
metadata:
  name: hub-acorn
  namespace: acorn
supportedRegions: ["local"]
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
---
apiVersion: internal.admin.acorn.io/v1
description: >-
  Hub-generated volume class representing ephemeral volumes not backed by a
  storage class
kind: ClusterVolumeClassInstance
metadata:
  name: ephemeral
---
apiVersion: internal.admin.acorn.io/v1
default: true
description: Hub-generated volume class representing the storage class ebs-retain
kind: ClusterVolumeClassInstance
metadata:
  name: ebs-retain
storageClassName: ebs-retain
---
apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: acorn-istio-plugin
  namespace: acorn
spec:
  image: ghcr.io/acorn-io/acorn-istio-plugin:prod
  autoUpgrade: true
  autoUpgradeInterval: 15s
  labels:
    - key: "sidecar.istio.io/inject"
      value: "false"
      resourceType: container
  permissions:
  - rules:
    - scopes:
      - cluster
      apiGroups:
      - ""
      resources:
      - namespaces
      verbs:
      - list
      - get
      - patch
      - update
      - watch
    - scopes:
      - cluster
      apiGroups:
      - coordination.k8s.io
      resources:
      - leases
      verbs:
      - get
      - create
      - update
    - scopes:
      - cluster
      apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - '*'
    - scopes:
      - cluster
      apiGroups:
      - ""
      resources:
      - pods/ephemeralcontainers
      verbs:
      - patch
      - update
    - scopes:
      - cluster
      apiGroups:
      - security.istio.io
      resources:
      - peerauthentications
      - authorizationpolicies
      verbs:
      - '*'
    - scopes:
      - cluster
      apiGroups:
      - networking.k8s.io
      resources:
      - ingresses
      verbs:
      - list
      - get
      - watch
      - update
    - scopes:
      - cluster
      apiGroups:
      - ""
      resources:
      - services
      verbs:
      - list
      - get
      - watch
    - scopes:
      - cluster
      apiGroups:
      - ""
      resources:
      - nodes
      verbs:
      - list
      - get
    serviceName: istio-plugin-controller
{{ end }}