{{ if .Values.istio }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-cni
  namespace: kube-system
spec:
  bootstrap: true
  chart: https://istio-release.storage.googleapis.com/charts/cni-1.17.1.tgz
  valuesContent: |
    cni:
      cniBinDir: /var/lib/rancher/k3s/data/current/bin
      cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-base
  namespace: istio-system
spec:
  bootstrap: true
  chart: https://istio-release.storage.googleapis.com/charts/base-1.17.1.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istiod
  namespace: istio-system
spec:
  bootstrap: true
  chart: https://acorn-io.github.io/hub-system-charts/istiod-1.17.1.tgz
  valuesContent: |
    pilot:
      autoscaleEnabled: false
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        key: taints.acorn.io/workload
    # configure telemetry to add the destination_port label to the istio_request_bytes metric
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              metrics:
              - name: request_bytes
                dimensions:
                  destination_port: destination.port
            outboundSidecar:
              metrics:
              - name: request_bytes
                dimensions:
                  destination_port: destination.port
    istio_cni:
      enabled: true
{{ end }}
