{{ if .Values.istio }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-cni
  namespace: kube-system
spec:
  bootstrap: true
  chart: https://istio-release.storage.googleapis.com/charts/cni-1.17.1.tgz
  valuesContent: |
    cni:
      cniBinDir: /var/lib/rancher/k3s/data/current/bin
      cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-base
  namespace: istio-system
spec:
  bootstrap: true
  chart: https://istio-release.storage.googleapis.com/charts/base-1.17.1.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istiod
  namespace: istio-system
spec:
  bootstrap: true
  chart: https://acorn-io.github.io/hub-system-charts/istiod-1.17.1.tgz
  valuesContent: |
    pilot:
      autoscaleEnabled: false
      replicaCount: 2
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        key: taints.acorn.io/workload
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: istio
                operator: In
                values:
                - pilot
            topologyKey: node-role.kubernetes.io/control-plane
    istio_cni:
      enabled: true
---
apiVersion: v1
kind: Secret
data:
  config: LSBqb2JfbmFtZTogJ2Vudm95LXN0YXRzJwogIG1ldHJpY3NfcGF0aDogL3N0YXRzL3Byb21ldGhldXMKICBrdWJlcm5ldGVzX3NkX2NvbmZpZ3M6CiAgLSByb2xlOiBwb2QKCiAgcmVsYWJlbF9jb25maWdzOgogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3BvZF9jb250YWluZXJfcG9ydF9uYW1lXQogICAgYWN0aW9uOiBrZWVwCiAgICByZWdleDogJy4qLWVudm95LXByb20nCg==
metadata:
  name: istio-proxy-scrape-config
  namespace: prometheus-operator
{{ end }}
