{{ if .Values.prometheus }}
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-operator
  labels:
    release: prometheus-operator
  annotations:
    istio-injection: disabled
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-operator
  namespace: kube-system
spec:
  bootstrap: true
  chart: https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-45.23.0/kube-prometheus-stack-45.23.0.tgz
  targetNamespace: prometheus-operator
  valuesContent: |
    prometheusOperator:
      serviceMonitor:
        metricRelabelings:
        # drop all metrics because we don't care about them
        # would be easier if we could just disable the ServiceMonitor but the chart does not provide that option
        - sourceLabels: [__name__]
          regex: '.*'
          action: drop
      admissionWebhooks:
        patch:
          podLabels:
            sidecar.istio.io/inject: "false"
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: "Exists"
      kubeletService:
        enabled: true
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: "Exists"
    kubelet:
      enabled: true
      serviceMonitor:
        cAdvisorMetricRelabelings:
        - source_labels: [id, pod]
          regex: .+;
          action: drop
        # only keep the metrics that we will use
        - sourceLabels: [__name__]
          action: keep
          regex: 'container_cpu_usage_seconds_total|container_memory_usage_bytes|container_network_(receive|transmit)_bytes_total'
    kube-state-metrics:
      tolerations:
      - key: taints.acorn.io/workload
        operator: "Exists"
      prometheus:
        monitor:
          # only keep the metrics that we will use
          metricRelabelings:
          - sourceLabels: [__name__]
            regex: 'kube_pod_labels'
            action: keep
      metricLabelsAllowlist:
      - namespaces=[acorn.io/app-name,acorn.io/app-namespace,acorn.io/container-name,acorn.io/project,acorn.io/project-name,hub.acorn.io/account-name]
      - deployments=[acorn.io/app-name,acorn.io/app-namespace,acorn.io/container-name,acorn.io/project,acorn.io/project-name,hub.acorn.io/account-name]
      - pods=[acorn.io/app-name,acorn.io/app-namespace,acorn.io/container-name,acorn.io/project,acorn.io/project-name,hub.acorn.io/account-name]
      - jobs=[acorn.io/app-name,acorn.io/app-namespace,acorn.io/container-name,acorn.io/project,acorn.io/project-name,hub.acorn.io/account-name]
      - cronjobs=[acorn.io/app-name,acorn.io/app-namespace,acorn.io/container-name,acorn.io/project,acorn.io/project-name,hub.acorn.io/account-name]
      - services=[acorn.io/app-name,acorn.io/app-namespace,acorn.io/container-name,acorn.io/project,acorn.io/project-name,hub.acorn.io/account-name]
      - secrets=[acorn.io/app-name,acorn.io/app-namespace,acorn.io/container-name,acorn.io/project,acorn.io/project-name,hub.acorn.io/account-name]
      - configmaps=[acorn.io/app-name,acorn.io/app-namespace,acorn.io/container-name,acorn.io/project,acorn.io/project-name,hub.acorn.io/account-name]
      - persistentvolumes=[acorn.io/app-name,acorn.io/app-namespace,acorn.io/container-name,acorn.io/project,acorn.io/project-name,hub.acorn.io/account-name]
      - persistentvolumeclaims=[acorn.io/app-name,acorn.io/app-namespace,acorn.io/container-name,acorn.io/project,acorn.io/project-name,hub.acorn.io/account-name]
    prometheus:
      enabled: false
    alertmanager:
      enabled: false
    grafana:
      enabled: false
    kubeApiServer:
      enabled: false
    coreDns: 
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeEtcd:
      enabled: false
    nodeExporter:
      enabled: false
    defaultRules:
      create: true
      rules:
        etcd: false
        k8s: false
        kubeApiserverAvailability: false
        kubeApiserverBurnrate: false
        kubeApiserverHistogram: false
        kubeApiserverSlos: false
        kubeControllerManager: false
        kubelet: false
        kubeProxy: false
        kubernetesApps: false
        kubernetesResources: false
        kubernetesStorage: false
        kubernetesSystem: false
        kubeScheduler: false
{{- end }}
